# Generated by Django 2.2.5 on 2019-10-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tilte',
            new_name='title',
        ),
    ]
